sudo: false
language: rust
cache:
  - cargo
  - directories:
    - .build-kcov
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - build-essential
      - libudev-dev
      - cmake
      - pkg-config
      - libcurl4-openssl-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

before_install:
  - pkg-config --list-all
  - pkg-config --libs libudev
  - pkg-config --modversion libudev
  - cargo install cargo-update || true
  - cargo install-update cargo-update
  - cargo install-update rustfmt
  - cargo install-update cargo-kcov
  - mkdir -p .build-kcov && cd $_ && cargo kcov --print-install-kcov-sh | sh

script:
  - |
    if [ "$TRAVIS_RUST_VERSION" == "nightly" ] ; then
      export ASAN_OPTIONS="detect_odr_violation=1:leak_check_at_exit=0:detect_leaks=0"
      #export RUSTFLAGS="-Z sanitizer=address"
    fi
  - |
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose
  - cargo kcov --verbose

after_success:
  - bash <(curl -s https://codecov.io/bash)
